### ISSUE TITLE
Pay To Many Broken

### ISSUE THREAD

**Issue by Praesidiarius** [kralverde/electrum-raven#8]
I use electrum-rvn-0.2.2-11-g6be8045-dirty-x86_64 on kali linux for a while now, to make my faucet payments. i need electrum because of the paytomany function. i have a CVS, what i copy to the "Pay to" window.

In the new 0.3.0 version from this repo (electrum-ravencoin-0.3.0-r2.AppImage),
 the pay to many is not working anymore. i always get error
"Invalid Lines found:" and then it lists all the addresses. here is an example:

`R9vJFUvdZqmYAPwYAfT4tqayioahPvEbQf,1.06470833
RUz33T5uF9H2YQEorCiCJvpHjDdeBW58AF,0.84129268
RGAAPaPmV4n7ZCeteAsYeiee9pwjwxqT3h,1.64042834
RDekG9wLUJq2B86PJFNErPUANjnx9MPwrK,1.37375772`

Would be awesome if that could be fixed, i am coder myself (sadly only nodejs/php/) so i cannot fix it on my own, but i will provide any information you need and willing to help to fix the bug. i would also contribute some raven if its fixed, as i really need the wallet.

**Comment by Praesidiarius** [comment]
i may add as a notice, that some of the addresses i pay to, also hold assets on that addresses - maybe that makes a difference because i see you have added lots of things regarding assets.

**Comment by kralverde** [comment]
Sorry, I just saw this. Would you mind remaking this error on https://github.com/Electrum-RVN-SIG/electrum-ravencoin
I will definitely be fixing this in the next release.

**Comment by raspy313** [comment]
So you have a faucet ? link ?
